# Generated by Django 5.1.1 on 2024-09-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
