# Generated by Django 5.1.1 on 2024-09-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
