# Generated by Django 5.1.1 on 2024-09-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_names_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='surname',
            field=models.CharField(default='', max_length=35),
        ),
    ]
