# Generated by Django 5.1.1 on 2024-09-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_name_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='name',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='name',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='name',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='name',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='name',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='name',
            name='postal_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
