# Generated by Django 5.1.1 on 2024-09-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_name_address_name_age_name_city_name_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
