# Generated by Django 5.1.1 on 2024-09-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_name_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='password2',
            field=models.CharField(default='', max_length=30),
        ),
    ]
