# Generated by Django 5.1.1 on 2024-09-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_name_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='address',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
